### ISSUE TITLE
No results for stationIDs 397 or 476

### ISSUE THREAD

**Issue by frankrende** [Elaniobro/MMM-nyc-transit#49]
I was able to setup MMM-nyc-transit and see train information for the default stations. I then modified them to point to my stationIDs, but no results are coming back. I tested other IDs and they seem to work fine, but I can't get data for 397 and 452.

```
 {
                        module: 'MMM-nyc-transit',
                        position: "bottom_bar",
                        header: "Next Train",
                        config: {
                                apiKey: 'tVTNdpMfuZ3O23NABScqt5jVAMtH3L8eKWDL1E47',
                                displayType: 'list',
                                mtaType: 'train',
                                stations: [
                                        {
                                                stationId: 397, //397 86 St 4,5,6 trains
                                                walkingTime: 8,
                                                dir: {
                                                        upTown: false,
                                                        downTown: true
                                                        }
                                        },
                                        {
                                                stationId: 452, //476 86 St Q train
                                                walkingTime: 3,
                                                dir: {
                                                        upTown: false,
                                                        downTown: true
                                                        }
                                        }
                                        ],
                                updateInterval: 300000
                        }
                },
```

I found this error after running `npm start`
```

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.14.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[09.02.2021 18:07.35.257] [LOG]   Starting MagicMirror: v2.14.0
[09.02.2021 18:07.35.277] [LOG]   Loading config ...
[09.02.2021 18:07.35.291] [LOG]   Loading module helpers ...
[09.02.2021 18:07.35.296] [LOG]   No helper found for module: alert.
[09.02.2021 18:07.35.553] [LOG]   Initializing new module helper ...
[09.02.2021 18:07.35.555] [LOG]   Module helper loaded: updatenotification
[09.02.2021 18:07.35.559] [LOG]   No helper found for module: clock.
[09.02.2021 18:07.36.278] [LOG]   Initializing new module helper ...
[09.02.2021 18:07.36.281] [LOG]   Module helper loaded: calendar
[09.02.2021 18:07.36.284] [LOG]   No helper found for module: currentweather.
[09.02.2021 18:07.36.286] [LOG]   No helper found for module: weatherforecast.
[09.02.2021 18:07.36.711] [LOG]   Initializing new module helper ...
[09.02.2021 18:07.36.714] [LOG]   Module helper loaded: MMM-nyc-transit
[09.02.2021 18:07.36.717] [LOG]   All module helpers loaded.
[09.02.2021 18:07.36.874] [LOG]   Starting server on port 8080 ...
[09.02.2021 18:07.36.900] [LOG]   Server started ...
[09.02.2021 18:07.36.904] [LOG]   Connecting socket for: updatenotification
[09.02.2021 18:07.36.907] [LOG]   Connecting socket for: calendar
[09.02.2021 18:07.36.909] [LOG]   Starting node helper for: calendar
[09.02.2021 18:07.36.912] [LOG]   Connecting socket for: MMM-nyc-transit
[09.02.2021 18:07.36.915] [LOG]   MMM-nyc-transit helper method started...
[09.02.2021 18:07.36.918] [LOG]   Sockets connected & modules started ...
[09.02.2021 18:07.37.363] [LOG]   Launching application.
[09.02.2021 18:07.37.403] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[09.02.2021 18:07.40.117] [LOG]   Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/frank.rende.iv%40gmail.com/private-72ffd5811e22993a637c8dc52a3a2baa/basic.ics - Interval: 300000
[09.02.2021 18:07.40.248] [LOG]   Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 300000
[09.02.2021 18:07.40.254] [LOG]   Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/8i1l16tj3ibb1qcsj248m89kbg%40group.calendar.google.com/private-8982dbb1f45ab9eaaeb36b31d879a072/basic.ics - Interval: 300000
[09.02.2021 18:07.40.286] [INFO]  Checking git for module: MMM-nyc-transit
[09.02.2021 18:07.41.612] [INFO]  Calendar-Fetcher: Broadcasting 2 events.
[09.02.2021 18:07.41.905] [INFO]  Calendar-Fetcher: Broadcasting 0 events.
[09.02.2021 18:07.42.400] [ERROR] (node:7414) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'name' of undefined
    at /home/pi/MagicMirror/modules/MMM-nyc-transit/node_helper.js:175:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[09.02.2021 18:07.42.402] [ERROR] (node:7414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[09.02.2021 18:07.42.403] [ERROR] (node:7414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[09.02.2021 18:07.43.832] [INFO]  Calendar-Fetcher: Broadcasting 3 events.
```

**Comment by frankrende** [comment]
I also noticed that the dependencies for mta-subway-stations and mta-subway-complexes is set at version 0.0.2 and 0.0.1 respectively, but both projects are actually on version 1.0.0 - could this be related?

**Comment by Elaniobro** [comment]
@frankrende  thank you for posting the 🐛 

Have/were you able to self resolve or is this issue still outstanding? If the latter, any new information you are able to provide is appreciated.

**Comment by frankrende** [comment]
Hi @Elaniobro -

I originally spent some time digging into the station labels, but didn't find anything stood out to me as problematic. However, I just started up my screen again to test and it's now working so I guess it can be resolved?

Thanks,
Frank

**Comment by Elaniobro** [comment]
@frankrende It could have been a timeout issue with the API, which I have seen while developing. 

Too many refreshes can cause it. 

I will keep this issue open for now, in case it presents it self again. Please let me know if it does, I will check back in a week or so.

**Comment by Elaniobro** [comment]
@frankrende, closing this ticket out since you have not reported any recurring or new issues. If you find one, please open up a new issue. Thank you for your support and feedback!
