### ISSUE TITLE
Multiple stations with same ID

### ISSUE THREAD

**Issue by george-dilthey** [Elaniobro/MMM-nyc-transit#81]
@Elaniobro Not sure if I should open up another bug here, but I'm getting errors with station ID 461. Spot checking other IDs seem to be fine, but 461 in my config file outputs the below when I start Magic Mirror. If I have 2 stations and one of them is 461, neither shows up. I just get the "Next Train" header. LMK if I can help debug at all. 

`[19.02.2022 13:19.17.799] [ERROR] (node:11075) UnhandledPromiseRejectionWarning: Error: Error: invalid wire type 4 at offset 1
    at /home/pi/Development/MagicMirror/modules/MMM-nyc-transit/node_helper.js:187:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

`[19.02.2022 13:19.17.802] [ERROR] (node:11075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)`

`[19.02.2022 13:19.17.805] [ERROR] (node:11075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

_Originally posted by @george-dilthey in https://github.com/Elaniobro/MMM-nyc-transit/issues/25#issuecomment-1046077224_

**Comment by dustbits** [comment]
I am having the same issue with station ID 611 and all I get is the Next Train header.

[09.03.2022 16:17.03.133] [ERROR] (node:17884) UnhandledPromiseRejectionWarning: Error: Error: invalid wire type 4 at offset 1
    at /home/pi/MagicMirror/modules/MMM-nyc-transit/node_helper.js:187:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[09.03.2022 16:17.03.134] [ERROR] (node:17884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Elaniobro** [comment]
Hi, is this issue still an issue?
